// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package model

import "encoding/json"
import "fmt"
import "reflect"
import "regexp"
import "time"

type ArpEntry struct {
	// Interface corresponds to the JSON schema field "interface".
	Interface *string `json:"interface,omitempty,omitzero" yaml:"interface,omitempty"`

	// IP corresponds to the JSON schema field "ip".
	IP string `json:"ip" yaml:"ip"`

	// MAC corresponds to the JSON schema field "mac".
	MAC MACAddress `json:"mac" yaml:"mac"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ArpEntry) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["ip"]; raw != nil && !ok {
		return fmt.Errorf("field ip in ArpEntry: required")
	}
	if _, ok := raw["mac"]; raw != nil && !ok {
		return fmt.Errorf("field mac in ArpEntry: required")
	}
	type Plain ArpEntry
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = ArpEntry(plain)
	return nil
}

// Vendor-neutral snapshot of one network device, as collected by an integration.
type Device struct {
	// Arp corresponds to the JSON schema field "arp".
	Arp []ArpEntry `json:"arp,omitempty,omitzero" yaml:"arp,omitempty"`

	// CPUPct corresponds to the JSON schema field "cpu_pct".
	CPUPct *float64 `json:"cpu_pct,omitempty,omitzero" yaml:"cpu_pct,omitempty"`

	// DhcpLeases corresponds to the JSON schema field "dhcp_leases".
	DhcpLeases []DhcpLease `json:"dhcp_leases,omitempty,omitzero" yaml:"dhcp_leases,omitempty"`

	// Fdb corresponds to the JSON schema field "fdb".
	Fdb []FdbEntry `json:"fdb,omitempty,omitzero" yaml:"fdb,omitempty"`

	// Management IP or hostname.
	Host *string `json:"host,omitempty,omitzero" yaml:"host,omitempty"`

	// End devices observed by this integration with extra details (network scans,
	// controllers).
	Hosts []Host `json:"hosts,omitempty,omitzero" yaml:"hosts,omitempty"`

	// Interfaces corresponds to the JSON schema field "interfaces".
	Interfaces []Interface `json:"interfaces,omitempty,omitzero" yaml:"interfaces,omitempty"`

	// All IP addresses owned by the device.
	IPs []string `json:"ips,omitempty,omitzero" yaml:"ips,omitempty"`

	// Stable unique id of the device within its integration (e.g. base MAC or
	// serial).
	Key string `json:"key" yaml:"key"`

	// All MAC addresses owned by the device.
	MACs []MACAddress `json:"macs,omitempty,omitzero" yaml:"macs,omitempty"`

	// MemPct corresponds to the JSON schema field "mem_pct".
	MemPct *float64 `json:"mem_pct,omitempty,omitzero" yaml:"mem_pct,omitempty"`

	// Model corresponds to the JSON schema field "model".
	Model *string `json:"model,omitempty,omitzero" yaml:"model,omitempty"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name" yaml:"name"`

	// Neighbors corresponds to the JSON schema field "neighbors".
	Neighbors []Neighbor `json:"neighbors,omitempty,omitzero" yaml:"neighbors,omitempty"`

	// OSVersion corresponds to the JSON schema field "os_version".
	OSVersion *string `json:"os_version,omitempty,omitzero" yaml:"os_version,omitempty"`

	// Role corresponds to the JSON schema field "role".
	Role *DeviceRole `json:"role,omitempty,omitzero" yaml:"role,omitempty"`

	// Serial corresponds to the JSON schema field "serial".
	Serial *string `json:"serial,omitempty,omitzero" yaml:"serial,omitempty"`

	// UptimeS corresponds to the JSON schema field "uptime_s".
	UptimeS *uint64 `json:"uptime_s,omitempty,omitzero" yaml:"uptime_s,omitempty"`

	// Vendor corresponds to the JSON schema field "vendor".
	Vendor *string `json:"vendor,omitempty,omitzero" yaml:"vendor,omitempty"`

	// WirelessClients corresponds to the JSON schema field "wireless_clients".
	WirelessClients []WirelessClient `json:"wireless_clients,omitempty,omitzero" yaml:"wireless_clients,omitempty"`
}

type DeviceRole string

const DeviceRoleAp DeviceRole = "ap"
const DeviceRoleFirewall DeviceRole = "firewall"
const DeviceRoleRouter DeviceRole = "router"
const DeviceRoleServer DeviceRole = "server"
const DeviceRoleSwitch DeviceRole = "switch"
const DeviceRoleUnknown DeviceRole = "unknown"

var enumValues_DeviceRole = []interface{}{
	"router",
	"switch",
	"ap",
	"firewall",
	"server",
	"unknown",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *DeviceRole) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_DeviceRole {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_DeviceRole, v)
	}
	*j = DeviceRole(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Device) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["key"]; raw != nil && !ok {
		return fmt.Errorf("field key in Device: required")
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in Device: required")
	}
	type Plain Device
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.CPUPct != nil && 100 < *plain.CPUPct {
		return fmt.Errorf("field %s: must be <= %v", "cpu_pct", 100)
	}
	if plain.CPUPct != nil && 0 > *plain.CPUPct {
		return fmt.Errorf("field %s: must be >= %v", "cpu_pct", 0)
	}
	if plain.MemPct != nil && 100 < *plain.MemPct {
		return fmt.Errorf("field %s: must be <= %v", "mem_pct", 100)
	}
	if plain.MemPct != nil && 0 > *plain.MemPct {
		return fmt.Errorf("field %s: must be >= %v", "mem_pct", 0)
	}
	*j = Device(plain)
	return nil
}

type DhcpLease struct {
	// ExpiresAt corresponds to the JSON schema field "expires_at".
	ExpiresAt *time.Time `json:"expires_at,omitempty,omitzero" yaml:"expires_at,omitempty"`

	// Hostname corresponds to the JSON schema field "hostname".
	Hostname *string `json:"hostname,omitempty,omitzero" yaml:"hostname,omitempty"`

	// IP corresponds to the JSON schema field "ip".
	IP string `json:"ip" yaml:"ip"`

	// MAC corresponds to the JSON schema field "mac".
	MAC MACAddress `json:"mac" yaml:"mac"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *DhcpLease) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["ip"]; raw != nil && !ok {
		return fmt.Errorf("field ip in DhcpLease: required")
	}
	if _, ok := raw["mac"]; raw != nil && !ok {
		return fmt.Errorf("field mac in DhcpLease: required")
	}
	type Plain DhcpLease
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = DhcpLease(plain)
	return nil
}

// Switch forwarding table entry: this MAC was learned on this port.
type FdbEntry struct {
	// MAC corresponds to the JSON schema field "mac".
	MAC MACAddress `json:"mac" yaml:"mac"`

	// Port corresponds to the JSON schema field "port".
	Port string `json:"port" yaml:"port"`

	// Vlan corresponds to the JSON schema field "vlan".
	Vlan *uint16 `json:"vlan,omitempty,omitzero" yaml:"vlan,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *FdbEntry) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["mac"]; raw != nil && !ok {
		return fmt.Errorf("field mac in FdbEntry: required")
	}
	if _, ok := raw["port"]; raw != nil && !ok {
		return fmt.Errorf("field port in FdbEntry: required")
	}
	type Plain FdbEntry
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.Vlan != nil && 4095 < *plain.Vlan {
		return fmt.Errorf("field %s: must be <= %v", "vlan", 4095)
	}
	*j = FdbEntry(plain)
	return nil
}

// One input of the 'add integration' form. Declared by core integrations and in
// plugin.yaml.
type FormField struct {
	// Default value; type must match the field type.
	Default interface{} `json:"default,omitempty,omitzero" yaml:"default,omitempty"`

	// Help corresponds to the JSON schema field "help".
	Help *string `json:"help,omitempty,omitzero" yaml:"help,omitempty"`

	// Key corresponds to the JSON schema field "key".
	Key string `json:"key" yaml:"key"`

	// Label corresponds to the JSON schema field "label".
	Label *string `json:"label,omitempty,omitzero" yaml:"label,omitempty"`

	// Choices for 'select' fields.
	Options []string `json:"options,omitempty,omitzero" yaml:"options,omitempty"`

	// Required corresponds to the JSON schema field "required".
	Required bool `json:"required,omitempty,omitzero" yaml:"required,omitempty"`

	// Type corresponds to the JSON schema field "type".
	Type FormFieldType `json:"type" yaml:"type"`
}

type FormFieldType string

const FormFieldTypeBool FormFieldType = "bool"
const FormFieldTypeHost FormFieldType = "host"
const FormFieldTypeInt FormFieldType = "int"
const FormFieldTypeSecret FormFieldType = "secret"
const FormFieldTypeSelect FormFieldType = "select"
const FormFieldTypeString FormFieldType = "string"
const FormFieldTypeURL FormFieldType = "url"

var enumValues_FormFieldType = []interface{}{
	"string",
	"secret",
	"host",
	"url",
	"int",
	"bool",
	"select",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *FormFieldType) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_FormFieldType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_FormFieldType, v)
	}
	*j = FormFieldType(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *FormField) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["key"]; raw != nil && !ok {
		return fmt.Errorf("field key in FormField: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in FormField: required")
	}
	type Plain FormField
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if matched, _ := regexp.MatchString(`^[a-z][a-z0-9_]*$`, string(plain.Key)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "Key", `^[a-z][a-z0-9_]*$`)
	}
	if v, ok := raw["required"]; !ok || v == nil {
		plain.Required = false
	}
	*j = FormField(plain)
	return nil
}

// An end device observed on the network, with whatever could be learned about it.
type Host struct {
	// Names from DNS, mDNS, NetBIOS, DHCP...
	Hostnames []string `json:"hostnames,omitempty,omitzero" yaml:"hostnames,omitempty"`

	// IP corresponds to the JSON schema field "ip".
	IP string `json:"ip" yaml:"ip"`

	// MAC corresponds to the JSON schema field "mac".
	MAC *MACAddress `json:"mac,omitempty,omitzero" yaml:"mac,omitempty"`

	// Manufacturer reported by the device itself (UPnP).
	Manufacturer *string `json:"manufacturer,omitempty,omitzero" yaml:"manufacturer,omitempty"`

	// Model corresponds to the JSON schema field "model".
	Model *string `json:"model,omitempty,omitzero" yaml:"model,omitempty"`

	// OpenPorts corresponds to the JSON schema field "open_ports".
	OpenPorts []uint16 `json:"open_ports,omitempty,omitzero" yaml:"open_ports,omitempty"`

	// OS corresponds to the JSON schema field "os".
	OS *string `json:"os,omitempty,omitzero" yaml:"os,omitempty"`

	// Advertised services, e.g. mDNS types like _airplay._tcp.
	Services []string `json:"services,omitempty,omitzero" yaml:"services,omitempty"`

	// How the host was found: arp, icmp, tcp, dns, mdns, ssdp, netbios.
	Sources []string `json:"sources,omitempty,omitzero" yaml:"sources,omitempty"`

	// Hardware vendor (e.g. from the MAC prefix).
	Vendor *string `json:"vendor,omitempty,omitzero" yaml:"vendor,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Host) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["ip"]; raw != nil && !ok {
		return fmt.Errorf("field ip in Host: required")
	}
	type Plain Host
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = Host(plain)
	return nil
}

type Interface struct {
	// Description corresponds to the JSON schema field "description".
	Description *string `json:"description,omitempty,omitzero" yaml:"description,omitempty"`

	// MAC corresponds to the JSON schema field "mac".
	MAC *MACAddress `json:"mac,omitempty,omitzero" yaml:"mac,omitempty"`

	// Readable port name (ifName), never a numeric index.
	Name string `json:"name" yaml:"name"`

	// Cumulative counter.
	RxBytes *uint64 `json:"rx_bytes,omitempty,omitzero" yaml:"rx_bytes,omitempty"`

	// RxErrors corresponds to the JSON schema field "rx_errors".
	RxErrors *uint64 `json:"rx_errors,omitempty,omitzero" yaml:"rx_errors,omitempty"`

	// SpeedMbps corresponds to the JSON schema field "speed_mbps".
	SpeedMbps *uint64 `json:"speed_mbps,omitempty,omitzero" yaml:"speed_mbps,omitempty"`

	// Cumulative counter.
	TxBytes *uint64 `json:"tx_bytes,omitempty,omitzero" yaml:"tx_bytes,omitempty"`

	// TxErrors corresponds to the JSON schema field "tx_errors".
	TxErrors *uint64 `json:"tx_errors,omitempty,omitzero" yaml:"tx_errors,omitempty"`

	// Type corresponds to the JSON schema field "type".
	Type *InterfaceType `json:"type,omitempty,omitzero" yaml:"type,omitempty"`

	// Operational status.
	Up *bool `json:"up,omitempty,omitzero" yaml:"up,omitempty"`
}

type InterfaceType string

const InterfaceTypeBridge InterfaceType = "bridge"
const InterfaceTypeEthernet InterfaceType = "ethernet"
const InterfaceTypeLag InterfaceType = "lag"
const InterfaceTypeLoopback InterfaceType = "loopback"
const InterfaceTypeOther InterfaceType = "other"
const InterfaceTypeTunnel InterfaceType = "tunnel"
const InterfaceTypeVlan InterfaceType = "vlan"
const InterfaceTypeWireless InterfaceType = "wireless"

var enumValues_InterfaceType = []interface{}{
	"ethernet",
	"wireless",
	"bridge",
	"vlan",
	"lag",
	"loopback",
	"tunnel",
	"other",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *InterfaceType) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_InterfaceType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_InterfaceType, v)
	}
	*j = InterfaceType(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Interface) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in Interface: required")
	}
	type Plain Interface
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = Interface(plain)
	return nil
}

// Lowercase, colon separated: aa:bb:cc:dd:ee:ff.
type MACAddress string

// UnmarshalJSON implements json.Unmarshaler.
func (j *MACAddress) UnmarshalJSON(value []byte) error {
	type Plain MACAddress
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if matched, _ := regexp.MatchString(`^[0-9a-f]{2}(:[0-9a-f]{2}){5}$`, string(plain)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "", `^[0-9a-f]{2}(:[0-9a-f]{2}){5}$`)
	}
	*j = MACAddress(plain)
	return nil
}

// A device seen through a discovery protocol.
type Neighbor struct {
	// LocalPort corresponds to the JSON schema field "local_port".
	LocalPort string `json:"local_port" yaml:"local_port"`

	// Protocol corresponds to the JSON schema field "protocol".
	Protocol *NeighborProtocol `json:"protocol,omitempty,omitzero" yaml:"protocol,omitempty"`

	// RemoteIP corresponds to the JSON schema field "remote_ip".
	RemoteIP *string `json:"remote_ip,omitempty,omitzero" yaml:"remote_ip,omitempty"`

	// Chassis MAC, when the chassis id is a MAC.
	RemoteMAC *MACAddress `json:"remote_mac,omitempty,omitzero" yaml:"remote_mac,omitempty"`

	// RemoteName corresponds to the JSON schema field "remote_name".
	RemoteName *string `json:"remote_name,omitempty,omitzero" yaml:"remote_name,omitempty"`

	// RemotePlatform corresponds to the JSON schema field "remote_platform".
	RemotePlatform *string `json:"remote_platform,omitempty,omitzero" yaml:"remote_platform,omitempty"`

	// RemotePort corresponds to the JSON schema field "remote_port".
	RemotePort *string `json:"remote_port,omitempty,omitzero" yaml:"remote_port,omitempty"`
}

type NeighborProtocol string

const NeighborProtocolCdp NeighborProtocol = "cdp"
const NeighborProtocolLldp NeighborProtocol = "lldp"
const NeighborProtocolMndp NeighborProtocol = "mndp"
const NeighborProtocolOther NeighborProtocol = "other"

var enumValues_NeighborProtocol = []interface{}{
	"lldp",
	"cdp",
	"mndp",
	"other",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *NeighborProtocol) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_NeighborProtocol {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_NeighborProtocol, v)
	}
	*j = NeighborProtocol(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Neighbor) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["local_port"]; raw != nil && !ok {
		return fmt.Errorf("field local_port in Neighbor: required")
	}
	type Plain Neighbor
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = Neighbor(plain)
	return nil
}

type PluginAction string

const PluginActionCollect PluginAction = "collect"
const PluginActionTest PluginAction = "test"

var enumValues_PluginAction = []interface{}{
	"collect",
	"test",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *PluginAction) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_PluginAction {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_PluginAction, v)
	}
	*j = PluginAction(v)
	return nil
}

// Contents of plugin.yaml at the root of a plugin repository.
type PluginManifest struct {
	// Author corresponds to the JSON schema field "author".
	Author *string `json:"author,omitempty,omitzero" yaml:"author,omitempty"`

	// Description corresponds to the JSON schema field "description".
	Description *string `json:"description,omitempty,omitzero" yaml:"description,omitempty"`

	// Python file executed by the core, relative to the plugin root.
	Entrypoint string `json:"entrypoint" yaml:"entrypoint"`

	// Fields corresponds to the JSON schema field "fields".
	Fields []FormField `json:"fields,omitempty,omitzero" yaml:"fields,omitempty"`

	// Homepage corresponds to the JSON schema field "homepage".
	Homepage *string `json:"homepage,omitempty,omitzero" yaml:"homepage,omitempty"`

	// ID corresponds to the JSON schema field "id".
	ID string `json:"id" yaml:"id"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name" yaml:"name"`

	// Plugin protocol version implemented by the plugin.
	Protocol uint64 `json:"protocol" yaml:"protocol"`

	// Semantic version of the plugin.
	Version string `json:"version" yaml:"version"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *PluginManifest) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["entrypoint"]; raw != nil && !ok {
		return fmt.Errorf("field entrypoint in PluginManifest: required")
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in PluginManifest: required")
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in PluginManifest: required")
	}
	if _, ok := raw["protocol"]; raw != nil && !ok {
		return fmt.Errorf("field protocol in PluginManifest: required")
	}
	if _, ok := raw["version"]; raw != nil && !ok {
		return fmt.Errorf("field version in PluginManifest: required")
	}
	type Plain PluginManifest
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if matched, _ := regexp.MatchString(`^[a-z][a-z0-9-]*$`, string(plain.ID)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "ID", `^[a-z][a-z0-9-]*$`)
	}
	if 1 > plain.Protocol {
		return fmt.Errorf("field %s: must be >= %v", "protocol", 1)
	}
	*j = PluginManifest(plain)
	return nil
}

// Written by the core as JSON to the plugin's stdin.
type PluginRequest struct {
	// Action corresponds to the JSON schema field "action".
	Action PluginAction `json:"action" yaml:"action"`

	// Values of the manifest fields, keyed by field key.
	Config PluginRequestConfig `json:"config" yaml:"config"`

	// Protocol corresponds to the JSON schema field "protocol".
	Protocol uint64 `json:"protocol" yaml:"protocol"`

	// Writable directory private to this integration, kept between runs (e.g. to
	// cache sessions).
	StateDir *string `json:"state_dir,omitempty,omitzero" yaml:"state_dir,omitempty"`
}

// Values of the manifest fields, keyed by field key.
type PluginRequestConfig map[string]interface{}

// UnmarshalJSON implements json.Unmarshaler.
func (j *PluginRequest) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["action"]; raw != nil && !ok {
		return fmt.Errorf("field action in PluginRequest: required")
	}
	if _, ok := raw["config"]; raw != nil && !ok {
		return fmt.Errorf("field config in PluginRequest: required")
	}
	if _, ok := raw["protocol"]; raw != nil && !ok {
		return fmt.Errorf("field protocol in PluginRequest: required")
	}
	type Plain PluginRequest
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if 1 > plain.Protocol {
		return fmt.Errorf("field %s: must be >= %v", "protocol", 1)
	}
	*j = PluginRequest(plain)
	return nil
}

// Written by the plugin as JSON to stdout. Exactly one of devices (collect),
// message (test) or error is set.
type PluginResponse struct {
	// Devices corresponds to the JSON schema field "devices".
	Devices []Device `json:"devices,omitempty,omitzero" yaml:"devices,omitempty"`

	// Error corresponds to the JSON schema field "error".
	Error *string `json:"error,omitempty,omitzero" yaml:"error,omitempty"`

	// Message corresponds to the JSON schema field "message".
	Message *string `json:"message,omitempty,omitzero" yaml:"message,omitempty"`
}

type WifiBand string

const WifiBandA24Ghz WifiBand = "2.4ghz"
const WifiBandA5Ghz WifiBand = "5ghz"
const WifiBandA6Ghz WifiBand = "6ghz"

var enumValues_WifiBand = []interface{}{
	"2.4ghz",
	"5ghz",
	"6ghz",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *WifiBand) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_WifiBand {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_WifiBand, v)
	}
	*j = WifiBand(v)
	return nil
}

type WirelessClient struct {
	// Band corresponds to the JSON schema field "band".
	Band *WifiBand `json:"band,omitempty,omitzero" yaml:"band,omitempty"`

	// Interface corresponds to the JSON schema field "interface".
	Interface *string `json:"interface,omitempty,omitzero" yaml:"interface,omitempty"`

	// MAC corresponds to the JSON schema field "mac".
	MAC MACAddress `json:"mac" yaml:"mac"`

	// RxRateMbps corresponds to the JSON schema field "rx_rate_mbps".
	RxRateMbps *float64 `json:"rx_rate_mbps,omitempty,omitzero" yaml:"rx_rate_mbps,omitempty"`

	// SignalDBM corresponds to the JSON schema field "signal_dbm".
	SignalDBM *int64 `json:"signal_dbm,omitempty,omitzero" yaml:"signal_dbm,omitempty"`

	// SSID corresponds to the JSON schema field "ssid".
	SSID *string `json:"ssid,omitempty,omitzero" yaml:"ssid,omitempty"`

	// TxRateMbps corresponds to the JSON schema field "tx_rate_mbps".
	TxRateMbps *float64 `json:"tx_rate_mbps,omitempty,omitzero" yaml:"tx_rate_mbps,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *WirelessClient) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["mac"]; raw != nil && !ok {
		return fmt.Errorf("field mac in WirelessClient: required")
	}
	type Plain WirelessClient
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.RxRateMbps != nil && 0 > *plain.RxRateMbps {
		return fmt.Errorf("field %s: must be >= %v", "rx_rate_mbps", 0)
	}
	if plain.SignalDBM != nil && 0 < *plain.SignalDBM {
		return fmt.Errorf("field %s: must be <= %v", "signal_dbm", 0)
	}
	if plain.TxRateMbps != nil && 0 > *plain.TxRateMbps {
		return fmt.Errorf("field %s: must be >= %v", "tx_rate_mbps", 0)
	}
	*j = WirelessClient(plain)
	return nil
}
