// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package model

import "encoding/json"
import "fmt"
import "reflect"
import "regexp"
import "time"

type ArpEntry struct {
	// Interface corresponds to the JSON schema field "interface".
	Interface *string `json:"interface,omitempty,omitzero" yaml:"interface,omitempty"`

	// IP corresponds to the JSON schema field "ip".
	IP string `json:"ip" yaml:"ip"`

	// MAC corresponds to the JSON schema field "mac".
	MAC MACAddress `json:"mac" yaml:"mac"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ArpEntry) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["ip"]; raw != nil && !ok {
		return fmt.Errorf("field ip in ArpEntry: required")
	}
	if _, ok := raw["mac"]; raw != nil && !ok {
		return fmt.Errorf("field mac in ArpEntry: required")
	}
	type Plain ArpEntry
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = ArpEntry(plain)
	return nil
}

// Vendor-neutral snapshot of one network device, as collected by an integration.
type Device struct {
	// Arp corresponds to the JSON schema field "arp".
	Arp []ArpEntry `json:"arp,omitempty,omitzero" yaml:"arp,omitempty"`

	// Logical CPUs (cores or threads); for a virtual machine or container, its vCPUs.
	CPUCount *uint64 `json:"cpu_count,omitempty,omitzero" yaml:"cpu_count,omitempty"`

	// CPUPct corresponds to the JSON schema field "cpu_pct".
	CPUPct *float64 `json:"cpu_pct,omitempty,omitzero" yaml:"cpu_pct,omitempty"`

	// DhcpLeases corresponds to the JSON schema field "dhcp_leases".
	DhcpLeases []DhcpLease `json:"dhcp_leases,omitempty,omitzero" yaml:"dhcp_leases,omitempty"`

	// Usage of each DHCP range.
	DhcpPools []DhcpPool `json:"dhcp_pools,omitempty,omitzero" yaml:"dhcp_pools,omitempty"`

	// Fdb corresponds to the JSON schema field "fdb".
	Fdb []FdbEntry `json:"fdb,omitempty,omitzero" yaml:"fdb,omitempty"`

	// FirewallStates corresponds to the JSON schema field "firewall_states".
	FirewallStates *FirewallStates `json:"firewall_states,omitempty,omitzero" yaml:"firewall_states,omitempty"`

	// Firmware corresponds to the JSON schema field "firmware".
	Firmware *Firmware `json:"firmware,omitempty,omitzero" yaml:"firmware,omitempty"`

	// Upstream gateways monitored by a router or firewall.
	Gateways []Gateway `json:"gateways,omitempty,omitzero" yaml:"gateways,omitempty"`

	// Management IP or hostname.
	Host *string `json:"host,omitempty,omitzero" yaml:"host,omitempty"`

	// End devices observed by this integration with extra details (network scans,
	// controllers).
	Hosts []Host `json:"hosts,omitempty,omitzero" yaml:"hosts,omitempty"`

	// Interfaces corresponds to the JSON schema field "interfaces".
	Interfaces []Interface `json:"interfaces,omitempty,omitzero" yaml:"interfaces,omitempty"`

	// All IP addresses owned by the device.
	IPs []string `json:"ips,omitempty,omitzero" yaml:"ips,omitempty"`

	// Stable unique id of the device within its integration (e.g. base MAC or
	// serial).
	Key string `json:"key" yaml:"key"`

	// System load averages over 1, 5 and 15 minutes.
	LoadAvg []float64 `json:"load_avg,omitempty,omitzero" yaml:"load_avg,omitempty"`

	// All MAC addresses owned by the device.
	MACs []MACAddress `json:"macs,omitempty,omitzero" yaml:"macs,omitempty"`

	// MemPct corresponds to the JSON schema field "mem_pct".
	MemPct *float64 `json:"mem_pct,omitempty,omitzero" yaml:"mem_pct,omitempty"`

	// Memory installed (or given to a virtual machine or container).
	MemTotalBytes *uint64 `json:"mem_total_bytes,omitempty,omitzero" yaml:"mem_total_bytes,omitempty"`

	// Memory in use.
	MemUsedBytes *uint64 `json:"mem_used_bytes,omitempty,omitzero" yaml:"mem_used_bytes,omitempty"`

	// Model corresponds to the JSON schema field "model".
	Model *string `json:"model,omitempty,omitzero" yaml:"model,omitempty"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name" yaml:"name"`

	// Neighbors corresponds to the JSON schema field "neighbors".
	Neighbors []Neighbor `json:"neighbors,omitempty,omitzero" yaml:"neighbors,omitempty"`

	// OSVersion corresponds to the JSON schema field "os_version".
	OSVersion *string `json:"os_version,omitempty,omitzero" yaml:"os_version,omitempty"`

	// Role corresponds to the JSON schema field "role".
	Role *DeviceRole `json:"role,omitempty,omitzero" yaml:"role,omitempty"`

	// Serial corresponds to the JSON schema field "serial".
	Serial *string `json:"serial,omitempty,omitzero" yaml:"serial,omitempty"`

	// Services running (or stopped) on the device.
	Services []Service `json:"services,omitempty,omitzero" yaml:"services,omitempty"`

	// Mounted file systems / volumes.
	Storage []Storage `json:"storage,omitempty,omitzero" yaml:"storage,omitempty"`

	// Swap in use.
	SwapPct *float64 `json:"swap_pct,omitempty,omitzero" yaml:"swap_pct,omitempty"`

	// Temperature sensors (CPU cores, disks, board).
	Temperatures []Temperature `json:"temperatures,omitempty,omitzero" yaml:"temperatures,omitempty"`

	// UptimeS corresponds to the JSON schema field "uptime_s".
	UptimeS *uint64 `json:"uptime_s,omitempty,omitzero" yaml:"uptime_s,omitempty"`

	// Vendor corresponds to the JSON schema field "vendor".
	Vendor *string `json:"vendor,omitempty,omitzero" yaml:"vendor,omitempty"`

	// VLANs defined on the device.
	Vlans []Vlan `json:"vlans,omitempty,omitzero" yaml:"vlans,omitempty"`

	// VPN tunnels and peers.
	VpnPeers []VpnPeer `json:"vpn_peers,omitempty,omitzero" yaml:"vpn_peers,omitempty"`

	// WirelessClients corresponds to the JSON schema field "wireless_clients".
	WirelessClients []WirelessClient `json:"wireless_clients,omitempty,omitzero" yaml:"wireless_clients,omitempty"`
}

type DeviceRole string

const DeviceRoleAp DeviceRole = "ap"
const DeviceRoleFirewall DeviceRole = "firewall"
const DeviceRoleRouter DeviceRole = "router"
const DeviceRoleServer DeviceRole = "server"
const DeviceRoleSwitch DeviceRole = "switch"
const DeviceRoleUnknown DeviceRole = "unknown"

var enumValues_DeviceRole = []interface{}{
	"router",
	"switch",
	"ap",
	"firewall",
	"server",
	"unknown",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *DeviceRole) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_DeviceRole {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_DeviceRole, v)
	}
	*j = DeviceRole(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Device) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["key"]; raw != nil && !ok {
		return fmt.Errorf("field key in Device: required")
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in Device: required")
	}
	type Plain Device
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.CPUCount != nil && 1 > *plain.CPUCount {
		return fmt.Errorf("field %s: must be >= %v", "cpu_count", 1)
	}
	if plain.CPUPct != nil && 100 < *plain.CPUPct {
		return fmt.Errorf("field %s: must be <= %v", "cpu_pct", 100)
	}
	if plain.CPUPct != nil && 0 > *plain.CPUPct {
		return fmt.Errorf("field %s: must be >= %v", "cpu_pct", 0)
	}
	if len(plain.LoadAvg) > 3 {
		return fmt.Errorf("field %s length: must be <= %d", "load_avg", 3)
	}
	if plain.MemPct != nil && 100 < *plain.MemPct {
		return fmt.Errorf("field %s: must be <= %v", "mem_pct", 100)
	}
	if plain.MemPct != nil && 0 > *plain.MemPct {
		return fmt.Errorf("field %s: must be >= %v", "mem_pct", 0)
	}
	if plain.SwapPct != nil && 100 < *plain.SwapPct {
		return fmt.Errorf("field %s: must be <= %v", "swap_pct", 100)
	}
	if plain.SwapPct != nil && 0 > *plain.SwapPct {
		return fmt.Errorf("field %s: must be >= %v", "swap_pct", 0)
	}
	*j = Device(plain)
	return nil
}

// What a device asks for when it requests an address (DHCP): the options it wants,
// in its own order, and what it says it is. Hints its operating system.
type DhcpFingerprint struct {
	// Option 12, the name the device gives itself.
	Hostname *string `json:"hostname,omitempty,omitzero" yaml:"hostname,omitempty"`

	// Option 55, the parameter request list, e.g.
	// "1,3,6,15,31,33,43,44,46,47,119,121,249,252".
	Params *string `json:"params,omitempty,omitzero" yaml:"params,omitempty"`

	// Option 60, the vendor class identifier, e.g. "android-dhcp-14" or "MSFT 5.0".
	VendorClass *string `json:"vendor_class,omitempty,omitzero" yaml:"vendor_class,omitempty"`
}

type DhcpLease struct {
	// ExpiresAt corresponds to the JSON schema field "expires_at".
	ExpiresAt *time.Time `json:"expires_at,omitempty,omitzero" yaml:"expires_at,omitempty"`

	// Hostname corresponds to the JSON schema field "hostname".
	Hostname *string `json:"hostname,omitempty,omitzero" yaml:"hostname,omitempty"`

	// IP corresponds to the JSON schema field "ip".
	IP string `json:"ip" yaml:"ip"`

	// MAC corresponds to the JSON schema field "mac".
	MAC MACAddress `json:"mac" yaml:"mac"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *DhcpLease) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["ip"]; raw != nil && !ok {
		return fmt.Errorf("field ip in DhcpLease: required")
	}
	if _, ok := raw["mac"]; raw != nil && !ok {
		return fmt.Errorf("field mac in DhcpLease: required")
	}
	type Plain DhcpLease
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = DhcpLease(plain)
	return nil
}

// Usage of a DHCP range.
type DhcpPool struct {
	// Interface or subnet the range serves, e.g. "LAN", "192.168.1.0/24".
	Network string `json:"network" yaml:"network"`

	// Addresses in the range.
	Total *uint64 `json:"total,omitempty,omitzero" yaml:"total,omitempty"`

	// Active leases.
	Used *uint64 `json:"used,omitempty,omitzero" yaml:"used,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *DhcpPool) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["network"]; raw != nil && !ok {
		return fmt.Errorf("field network in DhcpPool: required")
	}
	type Plain DhcpPool
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = DhcpPool(plain)
	return nil
}

// Switch forwarding table entry: this MAC was learned on this port.
type FdbEntry struct {
	// MAC corresponds to the JSON schema field "mac".
	MAC MACAddress `json:"mac" yaml:"mac"`

	// Port corresponds to the JSON schema field "port".
	Port string `json:"port" yaml:"port"`

	// Vlan corresponds to the JSON schema field "vlan".
	Vlan *uint16 `json:"vlan,omitempty,omitzero" yaml:"vlan,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *FdbEntry) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["mac"]; raw != nil && !ok {
		return fmt.Errorf("field mac in FdbEntry: required")
	}
	if _, ok := raw["port"]; raw != nil && !ok {
		return fmt.Errorf("field port in FdbEntry: required")
	}
	type Plain FdbEntry
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.Vlan != nil && 4095 < *plain.Vlan {
		return fmt.Errorf("field %s: must be <= %v", "vlan", 4095)
	}
	*j = FdbEntry(plain)
	return nil
}

// Connection tracking table of a firewall.
type FirewallStates struct {
	// Current corresponds to the JSON schema field "current".
	Current *uint64 `json:"current,omitempty,omitzero" yaml:"current,omitempty"`

	// Limit corresponds to the JSON schema field "limit".
	Limit *uint64 `json:"limit,omitempty,omitzero" yaml:"limit,omitempty"`
}

// Installed software/firmware version and available updates, as last checked by
// the device.
type Firmware struct {
	// When the device last checked for updates; absent if it never did.
	CheckedAt *time.Time `json:"checked_at,omitempty,omitzero" yaml:"checked_at,omitempty"`

	// Current corresponds to the JSON schema field "current".
	Current *string `json:"current,omitempty,omitzero" yaml:"current,omitempty"`

	// Newest version the device knows about.
	Latest *string `json:"latest,omitempty,omitzero" yaml:"latest,omitempty"`

	// Installing the updates requires a reboot.
	NeedsReboot *bool `json:"needs_reboot,omitempty,omitzero" yaml:"needs_reboot,omitempty"`

	// UpdateAvailable corresponds to the JSON schema field "update_available".
	UpdateAvailable *bool `json:"update_available,omitempty,omitzero" yaml:"update_available,omitempty"`

	// Number of pending package/firmware updates.
	Updates *uint64 `json:"updates,omitempty,omitzero" yaml:"updates,omitempty"`
}

// One input of the 'add integration' form. Declared by core integrations and in
// plugin.yaml.
type FormField struct {
	// Default value; type must match the field type.
	Default interface{} `json:"default,omitempty,omitzero" yaml:"default,omitempty"`

	// Section the field is shown under (e.g. "Methods"); fields without a group come
	// first.
	Group *string `json:"group,omitempty,omitzero" yaml:"group,omitempty"`

	// Help corresponds to the JSON schema field "help".
	Help *string `json:"help,omitempty,omitzero" yaml:"help,omitempty"`

	// Key corresponds to the JSON schema field "key".
	Key string `json:"key" yaml:"key"`

	// Label corresponds to the JSON schema field "label".
	Label *string `json:"label,omitempty,omitzero" yaml:"label,omitempty"`

	// Choices for 'select' fields.
	Options []string `json:"options,omitempty,omitzero" yaml:"options,omitempty"`

	// Required corresponds to the JSON schema field "required".
	Required bool `json:"required,omitempty,omitzero" yaml:"required,omitempty"`

	// Type corresponds to the JSON schema field "type".
	Type FormFieldType `json:"type" yaml:"type"`
}

type FormFieldType string

const FormFieldTypeBool FormFieldType = "bool"
const FormFieldTypeHost FormFieldType = "host"
const FormFieldTypeInt FormFieldType = "int"
const FormFieldTypeSecret FormFieldType = "secret"
const FormFieldTypeSelect FormFieldType = "select"
const FormFieldTypeString FormFieldType = "string"
const FormFieldTypeURL FormFieldType = "url"

var enumValues_FormFieldType = []interface{}{
	"string",
	"secret",
	"host",
	"url",
	"int",
	"bool",
	"select",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *FormFieldType) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_FormFieldType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_FormFieldType, v)
	}
	*j = FormFieldType(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *FormField) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["key"]; raw != nil && !ok {
		return fmt.Errorf("field key in FormField: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in FormField: required")
	}
	type Plain FormField
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if matched, _ := regexp.MatchString(`^[a-z][a-z0-9_]*$`, string(plain.Key)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "Key", `^[a-z][a-z0-9_]*$`)
	}
	if v, ok := raw["required"]; !ok || v == nil {
		plain.Required = false
	}
	*j = FormField(plain)
	return nil
}

// A gateway monitored by a router or firewall (e.g. WAN uplinks).
type Gateway struct {
	// Address corresponds to the JSON schema field "address".
	Address *string `json:"address,omitempty,omitzero" yaml:"address,omitempty"`

	// Interface the gateway is reached through.
	Interface *string `json:"interface,omitempty,omitzero" yaml:"interface,omitempty"`

	// LossPct corresponds to the JSON schema field "loss_pct".
	LossPct *float64 `json:"loss_pct,omitempty,omitzero" yaml:"loss_pct,omitempty"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name" yaml:"name"`

	// Average round-trip time.
	RttMs *float64 `json:"rtt_ms,omitempty,omitzero" yaml:"rtt_ms,omitempty"`

	// Status corresponds to the JSON schema field "status".
	Status GatewayStatus `json:"status" yaml:"status"`
}

type GatewayStatus string

const GatewayStatusDegraded GatewayStatus = "degraded"
const GatewayStatusDown GatewayStatus = "down"
const GatewayStatusUnknown GatewayStatus = "unknown"
const GatewayStatusUp GatewayStatus = "up"

var enumValues_GatewayStatus = []interface{}{
	"up",
	"degraded",
	"down",
	"unknown",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *GatewayStatus) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_GatewayStatus {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_GatewayStatus, v)
	}
	*j = GatewayStatus(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Gateway) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in Gateway: required")
	}
	if _, ok := raw["status"]; raw != nil && !ok {
		return fmt.Errorf("field status in Gateway: required")
	}
	type Plain Gateway
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.LossPct != nil && 100 < *plain.LossPct {
		return fmt.Errorf("field %s: must be <= %v", "loss_pct", 100)
	}
	if plain.LossPct != nil && 0 > *plain.LossPct {
		return fmt.Errorf("field %s: must be >= %v", "loss_pct", 0)
	}
	if plain.RttMs != nil && 0 > *plain.RttMs {
		return fmt.Errorf("field %s: must be >= %v", "rtt_ms", 0)
	}
	*j = Gateway(plain)
	return nil
}

// An end device observed on the network, with whatever could be learned about it.
type Host struct {
	// Service banners, e.g. the SSH version string.
	Banners []string `json:"banners,omitempty,omitzero" yaml:"banners,omitempty"`

	// Dhcp corresponds to the JSON schema field "dhcp".
	Dhcp *DhcpFingerprint `json:"dhcp,omitempty,omitzero" yaml:"dhcp,omitempty"`

	// Names from DNS, mDNS, NetBIOS, DHCP...
	Hostnames []string `json:"hostnames,omitempty,omitzero" yaml:"hostnames,omitempty"`

	// IP corresponds to the JSON schema field "ip".
	IP string `json:"ip" yaml:"ip"`

	// MAC corresponds to the JSON schema field "mac".
	MAC *MACAddress `json:"mac,omitempty,omitzero" yaml:"mac,omitempty"`

	// Manufacturer reported by the device itself (UPnP).
	Manufacturer *string `json:"manufacturer,omitempty,omitzero" yaml:"manufacturer,omitempty"`

	// Model corresponds to the JSON schema field "model".
	Model *string `json:"model,omitempty,omitzero" yaml:"model,omitempty"`

	// OpenPorts corresponds to the JSON schema field "open_ports".
	OpenPorts []uint16 `json:"open_ports,omitempty,omitzero" yaml:"open_ports,omitempty"`

	// OS corresponds to the JSON schema field "os".
	OS *string `json:"os,omitempty,omitzero" yaml:"os,omitempty"`

	// Advertised services, e.g. mDNS types like _airplay._tcp.
	Services []string `json:"services,omitempty,omitzero" yaml:"services,omitempty"`

	// How the host was found: arp, icmp, tcp, dns, mdns, ssdp, netbios, snmp.
	Sources []string `json:"sources,omitempty,omitzero" yaml:"sources,omitempty"`

	// Titles of the web interfaces found on the host (e.g. "TrueNAS", "Proxmox
	// Virtual Environment").
	Titles []string `json:"titles,omitempty,omitzero" yaml:"titles,omitempty"`

	// TTL of ICMP replies: hints the OS family (64 Unix-like, 128 Windows, 255
	// network gear).
	TTL *uint8 `json:"ttl,omitempty,omitzero" yaml:"ttl,omitempty"`

	// Hardware vendor (e.g. from the MAC prefix).
	Vendor *string `json:"vendor,omitempty,omitzero" yaml:"vendor,omitempty"`

	// Web interfaces found on the host, one per port.
	Web []WebService `json:"web,omitempty,omitzero" yaml:"web,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Host) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["ip"]; raw != nil && !ok {
		return fmt.Errorf("field ip in Host: required")
	}
	type Plain Host
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.TTL != nil && 1 > *plain.TTL {
		return fmt.Errorf("field %s: must be >= %v", "ttl", 1)
	}
	*j = Host(plain)
	return nil
}

type Interface struct {
	// Connector corresponds to the JSON schema field "connector".
	Connector *InterfaceConnector `json:"connector,omitempty,omitzero" yaml:"connector,omitempty"`

	// Description corresponds to the JSON schema field "description".
	Description *string `json:"description,omitempty,omitzero" yaml:"description,omitempty"`

	// Duplex corresponds to the JSON schema field "duplex".
	Duplex *InterfaceDuplex `json:"duplex,omitempty,omitzero" yaml:"duplex,omitempty"`

	// Addresses assigned to the interface, with prefix length (192.168.1.1/24).
	IPs []string `json:"ips,omitempty,omitzero" yaml:"ips,omitempty"`

	// MAC corresponds to the JSON schema field "mac".
	MAC *MACAddress `json:"mac,omitempty,omitzero" yaml:"mac,omitempty"`

	// Negotiated media as reported by the device, e.g. "1000baseT <full-duplex>".
	Media *string `json:"media,omitempty,omitzero" yaml:"media,omitempty"`

	// Ports a bridge or LAG is made of, by interface name.
	Members []string `json:"members,omitempty,omitzero" yaml:"members,omitempty"`

	// Readable port name (ifName), never a numeric index.
	Name string `json:"name" yaml:"name"`

	// Interface this one runs on: a VLAN's port, the port carrying a PPPoE link.
	Parent *string `json:"parent,omitempty,omitzero" yaml:"parent,omitempty"`

	// Cumulative counter.
	RxBytes *uint64 `json:"rx_bytes,omitempty,omitzero" yaml:"rx_bytes,omitempty"`

	// RxErrors corresponds to the JSON schema field "rx_errors".
	RxErrors *uint64 `json:"rx_errors,omitempty,omitzero" yaml:"rx_errors,omitempty"`

	// SpeedMbps corresponds to the JSON schema field "speed_mbps".
	SpeedMbps *uint64 `json:"speed_mbps,omitempty,omitzero" yaml:"speed_mbps,omitempty"`

	// Transceiver corresponds to the JSON schema field "transceiver".
	Transceiver *Transceiver `json:"transceiver,omitempty,omitzero" yaml:"transceiver,omitempty"`

	// Cumulative counter.
	TxBytes *uint64 `json:"tx_bytes,omitempty,omitzero" yaml:"tx_bytes,omitempty"`

	// TxErrors corresponds to the JSON schema field "tx_errors".
	TxErrors *uint64 `json:"tx_errors,omitempty,omitzero" yaml:"tx_errors,omitempty"`

	// Type corresponds to the JSON schema field "type".
	Type *InterfaceType `json:"type,omitempty,omitzero" yaml:"type,omitempty"`

	// Operational status.
	Up *bool `json:"up,omitempty,omitzero" yaml:"up,omitempty"`

	// VLAN id of a VLAN interface (e.g. igc1.20 → 20).
	Vlan *uint16 `json:"vlan,omitempty,omitzero" yaml:"vlan,omitempty"`

	// Vlans corresponds to the JSON schema field "vlans".
	Vlans *PortVlans `json:"vlans,omitempty,omitzero" yaml:"vlans,omitempty"`

	// Uplink to the internet (a WAN of a router or firewall).
	Wan *bool `json:"wan,omitempty,omitzero" yaml:"wan,omitempty"`
}

type InterfaceConnector string

const InterfaceConnectorQsfp InterfaceConnector = "qsfp"
const InterfaceConnectorRj45 InterfaceConnector = "rj45"
const InterfaceConnectorSfp InterfaceConnector = "sfp"

var enumValues_InterfaceConnector = []interface{}{
	"rj45",
	"sfp",
	"qsfp",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *InterfaceConnector) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_InterfaceConnector {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_InterfaceConnector, v)
	}
	*j = InterfaceConnector(v)
	return nil
}

type InterfaceDuplex string

const InterfaceDuplexFull InterfaceDuplex = "full"
const InterfaceDuplexHalf InterfaceDuplex = "half"

var enumValues_InterfaceDuplex = []interface{}{
	"full",
	"half",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *InterfaceDuplex) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_InterfaceDuplex {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_InterfaceDuplex, v)
	}
	*j = InterfaceDuplex(v)
	return nil
}

type InterfaceType string

const InterfaceTypeBridge InterfaceType = "bridge"
const InterfaceTypeEthernet InterfaceType = "ethernet"
const InterfaceTypeLag InterfaceType = "lag"
const InterfaceTypeLoopback InterfaceType = "loopback"
const InterfaceTypeOther InterfaceType = "other"
const InterfaceTypeTunnel InterfaceType = "tunnel"
const InterfaceTypeVlan InterfaceType = "vlan"
const InterfaceTypeWireless InterfaceType = "wireless"

var enumValues_InterfaceType = []interface{}{
	"ethernet",
	"wireless",
	"bridge",
	"vlan",
	"lag",
	"loopback",
	"tunnel",
	"other",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *InterfaceType) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_InterfaceType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_InterfaceType, v)
	}
	*j = InterfaceType(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Interface) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in Interface: required")
	}
	type Plain Interface
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.Vlan != nil && 4094 < *plain.Vlan {
		return fmt.Errorf("field %s: must be <= %v", "vlan", 4094)
	}
	if plain.Vlan != nil && 1 > *plain.Vlan {
		return fmt.Errorf("field %s: must be >= %v", "vlan", 1)
	}
	*j = Interface(plain)
	return nil
}

// Lowercase, colon separated: aa:bb:cc:dd:ee:ff.
type MACAddress string

// UnmarshalJSON implements json.Unmarshaler.
func (j *MACAddress) UnmarshalJSON(value []byte) error {
	type Plain MACAddress
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if matched, _ := regexp.MatchString(`^[0-9a-f]{2}(:[0-9a-f]{2}){5}$`, string(plain)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "", `^[0-9a-f]{2}(:[0-9a-f]{2}){5}$`)
	}
	*j = MACAddress(plain)
	return nil
}

// A device seen through a discovery protocol.
type Neighbor struct {
	// What the neighbor says it is (LLDP enabled capabilities): a desk phone
	// announces telephone, a switch bridge.
	Capabilities []NeighborCapability `json:"capabilities,omitempty,omitzero" yaml:"capabilities,omitempty"`

	// LocalPort corresponds to the JSON schema field "local_port".
	LocalPort string `json:"local_port" yaml:"local_port"`

	// Protocol corresponds to the JSON schema field "protocol".
	Protocol *NeighborProtocol `json:"protocol,omitempty,omitzero" yaml:"protocol,omitempty"`

	// RemoteIP corresponds to the JSON schema field "remote_ip".
	RemoteIP *string `json:"remote_ip,omitempty,omitzero" yaml:"remote_ip,omitempty"`

	// Chassis MAC, when the chassis id is a MAC.
	RemoteMAC *MACAddress `json:"remote_mac,omitempty,omitzero" yaml:"remote_mac,omitempty"`

	// RemoteName corresponds to the JSON schema field "remote_name".
	RemoteName *string `json:"remote_name,omitempty,omitzero" yaml:"remote_name,omitempty"`

	// RemotePlatform corresponds to the JSON schema field "remote_platform".
	RemotePlatform *string `json:"remote_platform,omitempty,omitzero" yaml:"remote_platform,omitempty"`

	// RemotePort corresponds to the JSON schema field "remote_port".
	RemotePort *string `json:"remote_port,omitempty,omitzero" yaml:"remote_port,omitempty"`
}

type NeighborCapability string

const NeighborCapabilityAp NeighborCapability = "ap"
const NeighborCapabilityBridge NeighborCapability = "bridge"
const NeighborCapabilityDocsis NeighborCapability = "docsis"
const NeighborCapabilityOther NeighborCapability = "other"
const NeighborCapabilityRepeater NeighborCapability = "repeater"
const NeighborCapabilityRouter NeighborCapability = "router"
const NeighborCapabilityStation NeighborCapability = "station"
const NeighborCapabilityTelephone NeighborCapability = "telephone"

var enumValues_NeighborCapability = []interface{}{
	"other",
	"repeater",
	"bridge",
	"ap",
	"router",
	"telephone",
	"docsis",
	"station",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *NeighborCapability) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_NeighborCapability {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_NeighborCapability, v)
	}
	*j = NeighborCapability(v)
	return nil
}

type NeighborProtocol string

const NeighborProtocolCdp NeighborProtocol = "cdp"
const NeighborProtocolLldp NeighborProtocol = "lldp"
const NeighborProtocolMndp NeighborProtocol = "mndp"
const NeighborProtocolOther NeighborProtocol = "other"

var enumValues_NeighborProtocol = []interface{}{
	"lldp",
	"cdp",
	"mndp",
	"other",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *NeighborProtocol) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_NeighborProtocol {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_NeighborProtocol, v)
	}
	*j = NeighborProtocol(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Neighbor) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["local_port"]; raw != nil && !ok {
		return fmt.Errorf("field local_port in Neighbor: required")
	}
	type Plain Neighbor
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = Neighbor(plain)
	return nil
}

type PluginAction string

const PluginActionCollect PluginAction = "collect"
const PluginActionTest PluginAction = "test"

var enumValues_PluginAction = []interface{}{
	"collect",
	"test",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *PluginAction) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_PluginAction {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_PluginAction, v)
	}
	*j = PluginAction(v)
	return nil
}

// Contents of plugin.yaml at the root of a plugin repository.
type PluginManifest struct {
	// Author corresponds to the JSON schema field "author".
	Author *string `json:"author,omitempty,omitzero" yaml:"author,omitempty"`

	// Description corresponds to the JSON schema field "description".
	Description *string `json:"description,omitempty,omitzero" yaml:"description,omitempty"`

	// Python file executed by the core, relative to the plugin root.
	Entrypoint string `json:"entrypoint" yaml:"entrypoint"`

	// Fields corresponds to the JSON schema field "fields".
	Fields []FormField `json:"fields,omitempty,omitzero" yaml:"fields,omitempty"`

	// Homepage corresponds to the JSON schema field "homepage".
	Homepage *string `json:"homepage,omitempty,omitzero" yaml:"homepage,omitempty"`

	// ID corresponds to the JSON schema field "id".
	ID string `json:"id" yaml:"id"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name" yaml:"name"`

	// Plugin protocol version implemented by the plugin.
	Protocol uint64 `json:"protocol" yaml:"protocol"`

	// Time limit per run; default 60.
	TimeoutS *uint16 `json:"timeout_s,omitempty,omitzero" yaml:"timeout_s,omitempty"`

	// Semantic version of the plugin.
	Version string `json:"version" yaml:"version"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *PluginManifest) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["entrypoint"]; raw != nil && !ok {
		return fmt.Errorf("field entrypoint in PluginManifest: required")
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in PluginManifest: required")
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in PluginManifest: required")
	}
	if _, ok := raw["protocol"]; raw != nil && !ok {
		return fmt.Errorf("field protocol in PluginManifest: required")
	}
	if _, ok := raw["version"]; raw != nil && !ok {
		return fmt.Errorf("field version in PluginManifest: required")
	}
	type Plain PluginManifest
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if matched, _ := regexp.MatchString(`^[a-z][a-z0-9-]*$`, string(plain.ID)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "ID", `^[a-z][a-z0-9-]*$`)
	}
	if 1 > plain.Protocol {
		return fmt.Errorf("field %s: must be >= %v", "protocol", 1)
	}
	if plain.TimeoutS != nil && 300 < *plain.TimeoutS {
		return fmt.Errorf("field %s: must be <= %v", "timeout_s", 300)
	}
	if plain.TimeoutS != nil && 5 > *plain.TimeoutS {
		return fmt.Errorf("field %s: must be >= %v", "timeout_s", 5)
	}
	*j = PluginManifest(plain)
	return nil
}

// Written by the core as JSON to the plugin's stdin.
type PluginRequest struct {
	// Action corresponds to the JSON schema field "action".
	Action PluginAction `json:"action" yaml:"action"`

	// Values of the manifest fields, keyed by field key.
	Config PluginRequestConfig `json:"config" yaml:"config"`

	// Protocol corresponds to the JSON schema field "protocol".
	Protocol uint64 `json:"protocol" yaml:"protocol"`

	// Writable directory private to this integration, kept between runs (e.g. to
	// cache sessions).
	StateDir *string `json:"state_dir,omitempty,omitzero" yaml:"state_dir,omitempty"`
}

// Values of the manifest fields, keyed by field key.
type PluginRequestConfig map[string]interface{}

// UnmarshalJSON implements json.Unmarshaler.
func (j *PluginRequest) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["action"]; raw != nil && !ok {
		return fmt.Errorf("field action in PluginRequest: required")
	}
	if _, ok := raw["config"]; raw != nil && !ok {
		return fmt.Errorf("field config in PluginRequest: required")
	}
	if _, ok := raw["protocol"]; raw != nil && !ok {
		return fmt.Errorf("field protocol in PluginRequest: required")
	}
	type Plain PluginRequest
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if 1 > plain.Protocol {
		return fmt.Errorf("field %s: must be >= %v", "protocol", 1)
	}
	*j = PluginRequest(plain)
	return nil
}

// Written by the plugin as JSON to stdout. Exactly one of devices (collect),
// message (test) or error is set.
type PluginResponse struct {
	// Devices corresponds to the JSON schema field "devices".
	Devices []Device `json:"devices,omitempty,omitzero" yaml:"devices,omitempty"`

	// Error corresponds to the JSON schema field "error".
	Error *string `json:"error,omitempty,omitzero" yaml:"error,omitempty"`

	// Message corresponds to the JSON schema field "message".
	Message *string `json:"message,omitempty,omitzero" yaml:"message,omitempty"`
}

// VLAN membership of a switch port.
type PortVlans struct {
	// VLANs carried tagged (trunk).
	Tagged []uint16 `json:"tagged,omitempty,omitzero" yaml:"tagged,omitempty"`

	// VLAN of untagged frames (PVID / access VLAN).
	Untagged *uint16 `json:"untagged,omitempty,omitzero" yaml:"untagged,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *PortVlans) UnmarshalJSON(value []byte) error {
	type Plain PortVlans
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.Untagged != nil && 4094 < *plain.Untagged {
		return fmt.Errorf("field %s: must be <= %v", "untagged", 4094)
	}
	if plain.Untagged != nil && 1 > *plain.Untagged {
		return fmt.Errorf("field %s: must be >= %v", "untagged", 1)
	}
	*j = PortVlans(plain)
	return nil
}

// A service (daemon) running on the device.
type Service struct {
	// Description corresponds to the JSON schema field "description".
	Description *string `json:"description,omitempty,omitzero" yaml:"description,omitempty"`

	// Configured to run (a stopped enabled service is a problem).
	Enabled *bool `json:"enabled,omitempty,omitzero" yaml:"enabled,omitempty"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name" yaml:"name"`

	// Running corresponds to the JSON schema field "running".
	Running *bool `json:"running,omitempty,omitzero" yaml:"running,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Service) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in Service: required")
	}
	type Plain Service
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = Service(plain)
	return nil
}

// A mounted file system or volume.
type Storage struct {
	// Device corresponds to the JSON schema field "device".
	Device *string `json:"device,omitempty,omitzero" yaml:"device,omitempty"`

	// FsType corresponds to the JSON schema field "fs_type".
	FsType *string `json:"fs_type,omitempty,omitzero" yaml:"fs_type,omitempty"`

	// Mount point, e.g. "/".
	Mount string `json:"mount" yaml:"mount"`

	// TotalBytes corresponds to the JSON schema field "total_bytes".
	TotalBytes *uint64 `json:"total_bytes,omitempty,omitzero" yaml:"total_bytes,omitempty"`

	// UsedBytes corresponds to the JSON schema field "used_bytes".
	UsedBytes *uint64 `json:"used_bytes,omitempty,omitzero" yaml:"used_bytes,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Storage) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["mount"]; raw != nil && !ok {
		return fmt.Errorf("field mount in Storage: required")
	}
	type Plain Storage
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = Storage(plain)
	return nil
}

// One temperature sensor.
type Temperature struct {
	// Celsius corresponds to the JSON schema field "celsius".
	Celsius float64 `json:"celsius" yaml:"celsius"`

	// Kind corresponds to the JSON schema field "kind".
	Kind *TemperatureKind `json:"kind,omitempty,omitzero" yaml:"kind,omitempty"`

	// Readable sensor name, e.g. "CPU 0", "ada0".
	Sensor string `json:"sensor" yaml:"sensor"`
}

type TemperatureKind string

const TemperatureKindBoard TemperatureKind = "board"
const TemperatureKindCPU TemperatureKind = "cpu"
const TemperatureKindDisk TemperatureKind = "disk"
const TemperatureKindOther TemperatureKind = "other"

var enumValues_TemperatureKind = []interface{}{
	"cpu",
	"disk",
	"board",
	"other",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *TemperatureKind) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_TemperatureKind {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_TemperatureKind, v)
	}
	*j = TemperatureKind(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Temperature) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["celsius"]; raw != nil && !ok {
		return fmt.Errorf("field celsius in Temperature: required")
	}
	if _, ok := raw["sensor"]; raw != nil && !ok {
		return fmt.Errorf("field sensor in Temperature: required")
	}
	type Plain Temperature
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = Temperature(plain)
	return nil
}

// A pluggable optic or DAC (SFP, SFP+, QSFP...) and its diagnostics (DOM / DDM),
// when the device reads them.
type Transceiver struct {
	// Laser bias current.
	BiasMa *float64 `json:"bias_ma,omitempty,omitzero" yaml:"bias_ma,omitempty"`

	// Part number.
	Part *string `json:"part,omitempty,omitzero" yaml:"part,omitempty"`

	// Received optical power.
	RxPowerDBM *float64 `json:"rx_power_dbm,omitempty,omitzero" yaml:"rx_power_dbm,omitempty"`

	// Receive power alarm threshold (low), when the module reports it.
	RxPowerLowDBM *float64 `json:"rx_power_low_dbm,omitempty,omitzero" yaml:"rx_power_low_dbm,omitempty"`

	// Serial corresponds to the JSON schema field "serial".
	Serial *string `json:"serial,omitempty,omitzero" yaml:"serial,omitempty"`

	// Module temperature.
	TemperatureC *float64 `json:"temperature_c,omitempty,omitzero" yaml:"temperature_c,omitempty"`

	// Transmitted optical power.
	TxPowerDBM *float64 `json:"tx_power_dbm,omitempty,omitzero" yaml:"tx_power_dbm,omitempty"`

	// e.g. "10GBASE-SR", "1000BASE-LX", "DAC".
	Type *string `json:"type,omitempty,omitzero" yaml:"type,omitempty"`

	// Vendor corresponds to the JSON schema field "vendor".
	Vendor *string `json:"vendor,omitempty,omitzero" yaml:"vendor,omitempty"`

	// Supply voltage.
	VoltageV *float64 `json:"voltage_v,omitempty,omitzero" yaml:"voltage_v,omitempty"`

	// WavelengthNm corresponds to the JSON schema field "wavelength_nm".
	WavelengthNm *float64 `json:"wavelength_nm,omitempty,omitzero" yaml:"wavelength_nm,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Transceiver) UnmarshalJSON(value []byte) error {
	type Plain Transceiver
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.WavelengthNm != nil && 0 > *plain.WavelengthNm {
		return fmt.Errorf("field %s: must be >= %v", "wavelength_nm", 0)
	}
	*j = Transceiver(plain)
	return nil
}

// A VLAN defined on the device.
type Vlan struct {
	// ID corresponds to the JSON schema field "id".
	ID uint16 `json:"id" yaml:"id"`

	// The device's interface for this VLAN, if any (router/firewall).
	Interface *string `json:"interface,omitempty,omitzero" yaml:"interface,omitempty"`

	// Name corresponds to the JSON schema field "name".
	Name *string `json:"name,omitempty,omitzero" yaml:"name,omitempty"`

	// e.g. "192.168.20.0/24".
	Subnet *string `json:"subnet,omitempty,omitzero" yaml:"subnet,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Vlan) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in Vlan: required")
	}
	type Plain Vlan
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if 4094 < plain.ID {
		return fmt.Errorf("field %s: must be <= %v", "id", 4094)
	}
	if 1 > plain.ID {
		return fmt.Errorf("field %s: must be >= %v", "id", 1)
	}
	*j = Vlan(plain)
	return nil
}

// A VPN tunnel or peer (WireGuard peer, OpenVPN client, IPsec tunnel).
type VpnPeer struct {
	// Tunnel address(es) of the peer.
	Address *string `json:"address,omitempty,omitzero" yaml:"address,omitempty"`

	// Connected corresponds to the JSON schema field "connected".
	Connected *bool `json:"connected,omitempty,omitzero" yaml:"connected,omitempty"`

	// Remote address (host:port).
	Endpoint *string `json:"endpoint,omitempty,omitzero" yaml:"endpoint,omitempty"`

	// LastHandshake corresponds to the JSON schema field "last_handshake".
	LastHandshake *time.Time `json:"last_handshake,omitempty,omitzero" yaml:"last_handshake,omitempty"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name" yaml:"name"`

	// Protocol corresponds to the JSON schema field "protocol".
	Protocol VpnPeerProtocol `json:"protocol" yaml:"protocol"`

	// RxBytes corresponds to the JSON schema field "rx_bytes".
	RxBytes *uint64 `json:"rx_bytes,omitempty,omitzero" yaml:"rx_bytes,omitempty"`

	// TxBytes corresponds to the JSON schema field "tx_bytes".
	TxBytes *uint64 `json:"tx_bytes,omitempty,omitzero" yaml:"tx_bytes,omitempty"`
}

type VpnPeerProtocol string

const VpnPeerProtocolIpsec VpnPeerProtocol = "ipsec"
const VpnPeerProtocolOpenvpn VpnPeerProtocol = "openvpn"
const VpnPeerProtocolOther VpnPeerProtocol = "other"
const VpnPeerProtocolWireguard VpnPeerProtocol = "wireguard"

var enumValues_VpnPeerProtocol = []interface{}{
	"wireguard",
	"openvpn",
	"ipsec",
	"other",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *VpnPeerProtocol) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_VpnPeerProtocol {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_VpnPeerProtocol, v)
	}
	*j = VpnPeerProtocol(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *VpnPeer) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in VpnPeer: required")
	}
	if _, ok := raw["protocol"]; raw != nil && !ok {
		return fmt.Errorf("field protocol in VpnPeer: required")
	}
	type Plain VpnPeer
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = VpnPeer(plain)
	return nil
}

// A web interface found on a host.
type WebService struct {
	// Port corresponds to the JSON schema field "port".
	Port uint16 `json:"port" yaml:"port"`

	// Title corresponds to the JSON schema field "title".
	Title *string `json:"title,omitempty,omitzero" yaml:"title,omitempty"`

	// URL corresponds to the JSON schema field "url".
	URL string `json:"url" yaml:"url"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *WebService) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["port"]; raw != nil && !ok {
		return fmt.Errorf("field port in WebService: required")
	}
	if _, ok := raw["url"]; raw != nil && !ok {
		return fmt.Errorf("field url in WebService: required")
	}
	type Plain WebService
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if 1 > plain.Port {
		return fmt.Errorf("field %s: must be >= %v", "port", 1)
	}
	*j = WebService(plain)
	return nil
}

type WifiBand string

const WifiBandA24Ghz WifiBand = "2.4ghz"
const WifiBandA5Ghz WifiBand = "5ghz"
const WifiBandA6Ghz WifiBand = "6ghz"

var enumValues_WifiBand = []interface{}{
	"2.4ghz",
	"5ghz",
	"6ghz",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *WifiBand) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_WifiBand {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_WifiBand, v)
	}
	*j = WifiBand(v)
	return nil
}

type WirelessClient struct {
	// Band corresponds to the JSON schema field "band".
	Band *WifiBand `json:"band,omitempty,omitzero" yaml:"band,omitempty"`

	// Interface corresponds to the JSON schema field "interface".
	Interface *string `json:"interface,omitempty,omitzero" yaml:"interface,omitempty"`

	// MAC corresponds to the JSON schema field "mac".
	MAC MACAddress `json:"mac" yaml:"mac"`

	// Current traffic the client downloads, in bits per second, as the access point
	// measures it.
	RxBps *uint64 `json:"rx_bps,omitempty,omitzero" yaml:"rx_bps,omitempty"`

	// Link (PHY) rate from the client to the access point.
	RxRateMbps *float64 `json:"rx_rate_mbps,omitempty,omitzero" yaml:"rx_rate_mbps,omitempty"`

	// SignalDBM corresponds to the JSON schema field "signal_dbm".
	SignalDBM *int64 `json:"signal_dbm,omitempty,omitzero" yaml:"signal_dbm,omitempty"`

	// SSID corresponds to the JSON schema field "ssid".
	SSID *string `json:"ssid,omitempty,omitzero" yaml:"ssid,omitempty"`

	// Current traffic the client uploads, in bits per second.
	TxBps *uint64 `json:"tx_bps,omitempty,omitzero" yaml:"tx_bps,omitempty"`

	// Link (PHY) rate from the access point to the client.
	TxRateMbps *float64 `json:"tx_rate_mbps,omitempty,omitzero" yaml:"tx_rate_mbps,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *WirelessClient) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["mac"]; raw != nil && !ok {
		return fmt.Errorf("field mac in WirelessClient: required")
	}
	type Plain WirelessClient
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.RxRateMbps != nil && 0 > *plain.RxRateMbps {
		return fmt.Errorf("field %s: must be >= %v", "rx_rate_mbps", 0)
	}
	if plain.SignalDBM != nil && 0 < *plain.SignalDBM {
		return fmt.Errorf("field %s: must be <= %v", "signal_dbm", 0)
	}
	if plain.TxRateMbps != nil && 0 > *plain.TxRateMbps {
		return fmt.Errorf("field %s: must be >= %v", "tx_rate_mbps", 0)
	}
	*j = WirelessClient(plain)
	return nil
}
