// Package appicons recognizes self-hosted apps from web page titles and
// serves their icons. Catalog and icons: Dashboard Icons (homarr-labs,
// Apache-2.0). The catalog is committed; the icon bundle is generated by
// `make icons` for release builds, and icons missing from it are downloaded
// once from the CDN and cached on disk.
package appicons

import (
	"archive/tar"
	"bytes"
	"compress/gzip"
	"context"
	"embed"
	"encoding/json"
	"errors"
	"io"
	"io/fs"
	"net/http"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"sync"
	"time"
	"unicode"
)

//go:embed catalog.json.gz
var catalogGz []byte

//go:embed all:bundle
var bundleFS embed.FS

// Entry is one icon of the catalog.
type Entry struct {
	Name       string   `json:"n"`
	Aliases    []string `json:"a,omitempty"`
	Categories []string `json:"c,omitempty"`
}

type phrase struct {
	words []string
	name  string
}

var (
	loadOnce sync.Once
	entries  map[string]Entry
	phrases  []phrase
)

// generic words are never enough to recognize an app on their own.
var generic = map[string]bool{
	"login": true, "log in": true, "sign in": true, "dashboard": true, "admin": true, "web": true,
	"app": true, "server": true, "home": true, "router": true, "status": true, "monitor": true,
	"index": true, "welcome": true, "default": true, "page": true, "portal": true, "settings": true,
	"setup": true, "error": true, "linux": true, "ubuntu": true, "debian": true, "nginx": true,
	"apache": true, "http": true, "https": true, "api": true, "ui": true, "web ui": true, "webui": true,
}

func load() {
	entries = map[string]Entry{}
	zr, err := gzip.NewReader(bytes.NewReader(catalogGz))
	if err != nil {
		return
	}
	var list []Entry
	if json.NewDecoder(zr).Decode(&list) != nil {
		return
	}
	for _, e := range list {
		entries[e.Name] = e
		add := func(text string) {
			w := words(text)
			p := strings.Join(w, " ")
			if len(p) < 3 || generic[p] {
				return
			}
			phrases = append(phrases, phrase{words: w, name: e.Name})
		}
		add(strings.ReplaceAll(e.Name, "-", " "))
		for _, a := range e.Aliases {
			add(a)
		}
	}
}

func words(s string) []string {
	return strings.FieldsFunc(strings.ToLower(s), func(r rune) bool {
		return !unicode.IsLetter(r) && !unicode.IsDigit(r)
	})
}

// Known reports whether the catalog has an icon with this name.
func Known(name string) bool {
	loadOnce.Do(load)
	_, ok := entries[name]
	return ok
}

// Names returns every icon name of the catalog, sorted.
func Names() []string {
	loadOnce.Do(load)
	out := make([]string, 0, len(entries))
	for n := range entries {
		out = append(out, n)
	}
	sort.Strings(out)
	return out
}

// Count returns the number of icons in the catalog.
func Count() int {
	loadOnce.Do(load)
	return len(entries)
}

// Match recognizes the app named in a web page title, e.g. "qBittorrent WebUI"
// -> "qbittorrent". The longest name found as whole words wins.
func Match(title string) (string, bool) {
	loadOnce.Do(load)
	t := words(title)
	best, bestLen := "", 0
	for _, p := range phrases {
		if containsWords(t, p.words) {
			n := len(strings.Join(p.words, " "))
			if n > bestLen || (n == bestLen && p.name < best) {
				best, bestLen = p.name, n
			}
		}
	}
	return best, best != ""
}

func containsWords(text, sub []string) bool {
	for i := 0; i+len(sub) <= len(text); i++ {
		match := true
		for j := range sub {
			if text[i+j] != sub[j] {
				match = false
				break
			}
		}
		if match {
			return true
		}
	}
	return false
}

// DisplayName returns a readable name for an icon name: "home-assistant" ->
// "Home Assistant", keeping the spelling used in the title when available
// ("qBittorrent WebUI" -> "qBittorrent").
func DisplayName(name, title string) string {
	if title != "" {
		want := strings.ReplaceAll(name, "-", " ")
		tw := strings.FieldsFunc(title, func(r rune) bool { return !unicode.IsLetter(r) && !unicode.IsDigit(r) })
		n := len(strings.Fields(want))
		for i := 0; i+n <= len(tw); i++ {
			if strings.EqualFold(strings.Join(tw[i:i+n], " "), want) {
				return strings.Join(tw[i:i+n], " ")
			}
		}
	}
	parts := strings.Split(name, "-")
	for i, p := range parts {
		if p != "" {
			parts[i] = strings.ToUpper(p[:1]) + p[1:]
		}
	}
	return strings.Join(parts, " ")
}

// --- serving icons ---

var validName = regexp.MustCompile(`^[a-z0-9][a-z0-9-]{0,80}$`)

// Server serves icons from the embedded bundle, a disk cache or the CDN.
type Server struct {
	CacheDir string // e.g. <data dir>/icons
	CDN      string // default jsDelivr; empty string in tests disables downloads
	Offline  bool   // never download

	bundleOnce sync.Once
	bundle     map[string][]byte
	mu         sync.Mutex
	client     *http.Client
}

const defaultCDN = "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg"

func NewServer(cacheDir string) *Server {
	return &Server{CacheDir: cacheDir, CDN: defaultCDN, client: &http.Client{Timeout: 8 * time.Second}}
}

func (s *Server) loadBundle() {
	s.bundle = map[string][]byte{}
	b, err := fs.ReadFile(bundleFS, "bundle/icons.tar.gz")
	if err != nil {
		return // development build: no bundle
	}
	zr, err := gzip.NewReader(bytes.NewReader(b))
	if err != nil {
		return
	}
	tr := tar.NewReader(zr)
	for {
		h, err := tr.Next()
		if err != nil {
			return
		}
		data, err := io.ReadAll(tr)
		if err == nil {
			s.bundle[strings.TrimSuffix(h.Name, ".svg")] = data
		}
	}
}

// ErrUnknown is returned for names that are not in the catalog.
var ErrUnknown = errors.New("unknown icon")

// Icon returns the SVG of an icon.
func (s *Server) Icon(ctx context.Context, name string) ([]byte, error) {
	if !validName.MatchString(name) || !Known(name) {
		return nil, ErrUnknown
	}
	s.bundleOnce.Do(s.loadBundle)
	if b, ok := s.bundle[name]; ok {
		return b, nil
	}
	path := filepath.Join(s.CacheDir, name+".svg")
	if b, err := os.ReadFile(path); err == nil {
		return b, nil
	}
	if s.Offline || s.CDN == "" {
		return nil, ErrUnknown
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, s.CDN+"/"+name+".svg", nil)
	if err != nil {
		return nil, err
	}
	client := s.client
	if client == nil {
		client = http.DefaultClient
	}
	resp, err := client.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return nil, ErrUnknown
	}
	b, err := io.ReadAll(io.LimitReader(resp.Body, 4<<20))
	if err != nil {
		return nil, err
	}
	if err := os.MkdirAll(s.CacheDir, 0o750); err == nil {
		_ = os.WriteFile(path, b, 0o640)
	}
	return b, nil
}

// ServeHTTP serves GET /api/icons/{name}.svg (the caller routes the path).
func (s *Server) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	name := strings.TrimSuffix(r.PathValue("name"), ".svg")
	b, err := s.Icon(r.Context(), name)
	if err != nil {
		http.NotFound(w, r)
		return
	}
	w.Header().Set("Content-Type", "image/svg+xml")
	w.Header().Set("Cache-Control", "public, max-age=604800")
	// SVG can contain scripts: never run them, even if opened directly.
	w.Header().Set("Content-Security-Policy", "default-src 'none'; style-src 'unsafe-inline'; img-src data:")
	w.Header().Set("X-Content-Type-Options", "nosniff")
	_, _ = w.Write(b)
}
