# generated by datamodel-codegen:
#   filename:  omini.schema.json

from __future__ import annotations
from typing import Annotated, Any, Literal
from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class OminiDataContract(RootModel[Any]):
    root: Annotated[Any, Field(title="Omini data contract")]
    """
    Single source of truth for the data exchanged between the Omini core and integrations/plugins. Go types and Python models are generated from this file (make generate).
    """


class MacAddress(RootModel[str]):
    root: Annotated[str, Field(pattern="^[0-9a-f]{2}(:[0-9a-f]{2}){5}$")]
    """
    Lowercase, colon separated: aa:bb:cc:dd:ee:ff.
    """


class FdbEntry(BaseModel):
    """
    Switch forwarding table entry: this MAC was learned on this port.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    mac: Annotated[str, Field(pattern="^[0-9a-f]{2}(:[0-9a-f]{2}){5}$")]
    """
    Lowercase, colon separated: aa:bb:cc:dd:ee:ff.
    """
    port: str
    vlan: Annotated[int | None, Field(ge=0, le=4095)] = None


class ArpEntry(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ip: str
    mac: Annotated[str, Field(pattern="^[0-9a-f]{2}(:[0-9a-f]{2}){5}$")]
    """
    Lowercase, colon separated: aa:bb:cc:dd:ee:ff.
    """
    interface: str | None = None


class DhcpLease(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ip: str
    mac: Annotated[str, Field(pattern="^[0-9a-f]{2}(:[0-9a-f]{2}){5}$")]
    """
    Lowercase, colon separated: aa:bb:cc:dd:ee:ff.
    """
    hostname: str | None = None
    expires_at: AwareDatetime | None = None


class OpenPort(RootModel[int]):
    root: Annotated[int, Field(ge=1, le=65535)]


class DhcpFingerprint(BaseModel):
    """
    What a device asks for when it requests an address (DHCP): the options it wants, in its own order, and what it says it is. Hints its operating system.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    params: str | None = None
    """
    Option 55, the parameter request list, e.g. "1,3,6,15,31,33,43,44,46,47,119,121,249,252".
    """
    vendor_class: str | None = None
    """
    Option 60, the vendor class identifier, e.g. "android-dhcp-14" or "MSFT 5.0".
    """
    hostname: str | None = None
    """
    Option 12, the name the device gives itself.
    """


class WebService(BaseModel):
    """
    A web interface found on a host.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    port: Annotated[int, Field(ge=1, le=65535)]
    url: str
    title: str | None = None


class Temperature(BaseModel):
    """
    One temperature sensor.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    sensor: str
    """
    Readable sensor name, e.g. "CPU 0", "ada0".
    """
    kind: Literal["cpu", "disk", "board", "other"] | None = None
    celsius: float


class Storage(BaseModel):
    """
    A mounted file system or volume.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    mount: str
    """
    Mount point, e.g. "/".
    """
    device: str | None = None
    fs_type: str | None = None
    total_bytes: Annotated[int | None, Field(ge=0)] = None
    used_bytes: Annotated[int | None, Field(ge=0)] = None


class Firmware(BaseModel):
    """
    Installed software/firmware version and available updates, as last checked by the device.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    current: str | None = None
    latest: str | None = None
    """
    Newest version the device knows about.
    """
    update_available: bool | None = None
    updates: Annotated[int | None, Field(ge=0)] = None
    """
    Number of pending package/firmware updates.
    """
    needs_reboot: bool | None = None
    """
    Installing the updates requires a reboot.
    """
    checked_at: AwareDatetime | None = None
    """
    When the device last checked for updates; absent if it never did.
    """


class TaggedItem(RootModel[int]):
    root: Annotated[int, Field(ge=1, le=4094)]


class PortVlans(BaseModel):
    """
    VLAN membership of a switch port.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    untagged: Annotated[int | None, Field(ge=1, le=4094)] = None
    """
    VLAN of untagged frames (PVID / access VLAN).
    """
    tagged: list[TaggedItem] | None = None
    """
    VLANs carried tagged (trunk).
    """


class Transceiver(BaseModel):
    """
    A pluggable optic or DAC (SFP, SFP+, QSFP...) and its diagnostics (DOM / DDM), when the device reads them.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    vendor: str | None = None
    part: str | None = None
    """
    Part number.
    """
    serial: str | None = None
    type: str | None = None
    """
    e.g. "10GBASE-SR", "1000BASE-LX", "DAC".
    """
    wavelength_nm: Annotated[float | None, Field(ge=0.0)] = None
    temperature_c: float | None = None
    """
    Module temperature.
    """
    voltage_v: float | None = None
    """
    Supply voltage.
    """
    bias_ma: float | None = None
    """
    Laser bias current.
    """
    tx_power_dbm: float | None = None
    """
    Transmitted optical power.
    """
    rx_power_dbm: float | None = None
    """
    Received optical power.
    """
    rx_power_low_dbm: float | None = None
    """
    Receive power alarm threshold (low), when the module reports it.
    """


class Vlan(BaseModel):
    """
    A VLAN defined on the device.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    id: Annotated[int, Field(ge=1, le=4094)]
    name: str | None = None
    interface: str | None = None
    """
    The device's interface for this VLAN, if any (router/firewall).
    """
    subnet: str | None = None
    """
    e.g. "192.168.20.0/24".
    """


class Service(BaseModel):
    """
    A service (daemon) running on the device.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    name: str
    description: str | None = None
    running: bool | None = None
    enabled: bool | None = None
    """
    Configured to run (a stopped enabled service is a problem).
    """


class VpnPeer(BaseModel):
    """
    A VPN tunnel or peer (WireGuard peer, OpenVPN client, IPsec tunnel).
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    name: str
    protocol: Literal["wireguard", "openvpn", "ipsec", "other"]
    endpoint: str | None = None
    """
    Remote address (host:port).
    """
    address: str | None = None
    """
    Tunnel address(es) of the peer.
    """
    connected: bool | None = None
    last_handshake: AwareDatetime | None = None
    rx_bytes: Annotated[int | None, Field(ge=0)] = None
    tx_bytes: Annotated[int | None, Field(ge=0)] = None


class DhcpPool(BaseModel):
    """
    Usage of a DHCP range.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    network: str
    """
    Interface or subnet the range serves, e.g. "LAN", "192.168.1.0/24".
    """
    total: Annotated[int | None, Field(ge=0)] = None
    """
    Addresses in the range.
    """
    used: Annotated[int | None, Field(ge=0)] = None
    """
    Active leases.
    """


class FirewallStates(BaseModel):
    """
    Connection tracking table of a firewall.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    current: Annotated[int | None, Field(ge=0)] = None
    limit: Annotated[int | None, Field(ge=0)] = None


class Interface(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str
    """
    Readable port name (ifName), never a numeric index.
    """
    description: str | None = None
    type: (
        Literal["ethernet", "wireless", "bridge", "vlan", "lag", "loopback", "tunnel", "other"]
        | None
    ) = None
    connector: Literal["rj45", "sfp", "qsfp"] | None = None
    """
    Physical connector of a port.
    """
    mac: Annotated[str | None, Field(pattern="^[0-9a-f]{2}(:[0-9a-f]{2}){5}$")] = None
    """
    Lowercase, colon separated: aa:bb:cc:dd:ee:ff.
    """
    ips: list[str] | None = None
    """
    Addresses assigned to the interface, with prefix length (192.168.1.1/24).
    """
    wan: bool | None = None
    """
    Uplink to the internet (a WAN of a router or firewall).
    """
    parent: str | None = None
    """
    Interface this one runs on: a VLAN's port, the port carrying a PPPoE link.
    """
    members: list[str] | None = None
    """
    Ports a bridge or LAG is made of, by interface name.
    """
    up: bool | None = None
    """
    Operational status.
    """
    speed_mbps: Annotated[int | None, Field(ge=0)] = None
    duplex: Literal["full", "half"] | None = None
    media: str | None = None
    """
    Negotiated media as reported by the device, e.g. "1000baseT <full-duplex>".
    """
    rx_bytes: Annotated[int | None, Field(ge=0)] = None
    """
    Cumulative counter.
    """
    tx_bytes: Annotated[int | None, Field(ge=0)] = None
    """
    Cumulative counter.
    """
    rx_errors: Annotated[int | None, Field(ge=0)] = None
    tx_errors: Annotated[int | None, Field(ge=0)] = None
    vlan: Annotated[int | None, Field(ge=1, le=4094)] = None
    """
    VLAN id of a VLAN interface (e.g. igc1.20 → 20).
    """
    vlans: PortVlans | None = None
    transceiver: Transceiver | None = None


class Neighbor(BaseModel):
    """
    A device seen through a discovery protocol.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    local_port: str
    protocol: Literal["lldp", "cdp", "mndp", "other"] | None = None
    remote_name: str | None = None
    remote_port: str | None = None
    remote_mac: Annotated[str | None, Field(pattern="^[0-9a-f]{2}(:[0-9a-f]{2}){5}$")] = None
    """
    Chassis MAC, when the chassis id is a MAC.
    """
    remote_ip: str | None = None
    remote_platform: str | None = None
    capabilities: (
        list[
            Literal["other", "repeater", "bridge", "ap", "router", "telephone", "docsis", "station"]
        ]
        | None
    ) = None
    """
    What the neighbor says it is (LLDP enabled capabilities): a desk phone announces telephone, a switch bridge.
    """


class WirelessClient(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    mac: Annotated[str, Field(pattern="^[0-9a-f]{2}(:[0-9a-f]{2}){5}$")]
    """
    Lowercase, colon separated: aa:bb:cc:dd:ee:ff.
    """
    interface: str | None = None
    ssid: str | None = None
    band: Literal["2.4ghz", "5ghz", "6ghz"] | None = None
    signal_dbm: Annotated[int | None, Field(le=0)] = None
    tx_rate_mbps: Annotated[float | None, Field(ge=0.0)] = None
    """
    Link (PHY) rate from the access point to the client.
    """
    rx_rate_mbps: Annotated[float | None, Field(ge=0.0)] = None
    """
    Link (PHY) rate from the client to the access point.
    """
    rx_bps: Annotated[int | None, Field(ge=0)] = None
    """
    Current traffic the client downloads, in bits per second, as the access point measures it.
    """
    tx_bps: Annotated[int | None, Field(ge=0)] = None
    """
    Current traffic the client uploads, in bits per second.
    """


class Gateway(BaseModel):
    """
    A gateway monitored by a router or firewall (e.g. WAN uplinks).
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    name: str
    interface: str | None = None
    """
    Interface the gateway is reached through.
    """
    address: str | None = None
    status: Literal["up", "degraded", "down", "unknown"]
    rtt_ms: Annotated[float | None, Field(ge=0.0)] = None
    """
    Average round-trip time.
    """
    loss_pct: Annotated[float | None, Field(ge=0.0, le=100.0)] = None


class FormField(BaseModel):
    """
    One input of the 'add integration' form. Declared by core integrations and in plugin.yaml.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    key: Annotated[str, Field(pattern="^[a-z][a-z0-9_]*$")]
    type: Literal["string", "secret", "host", "url", "int", "bool", "select"]
    label: str | None = None
    help: str | None = None
    required: bool | None = False
    default: Any | None = None
    """
    Default value; type must match the field type.
    """
    options: list[str] | None = None
    """
    Choices for 'select' fields.
    """
    group: str | None = None
    """
    Section the field is shown under (e.g. "Methods"); fields without a group come first.
    """


class PluginManifest(BaseModel):
    """
    Contents of plugin.yaml at the root of a plugin repository.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    id: Annotated[str, Field(pattern="^[a-z][a-z0-9-]*$")]
    name: str
    version: str
    """
    Semantic version of the plugin.
    """
    protocol: Annotated[int, Field(ge=1)]
    """
    Plugin protocol version implemented by the plugin.
    """
    entrypoint: str
    """
    Python file executed by the core, relative to the plugin root.
    """
    timeout_s: Annotated[int | None, Field(ge=5, le=300)] = None
    """
    Time limit per run; default 60.
    """
    description: str | None = None
    author: str | None = None
    homepage: str | None = None
    fields: list[FormField] | None = None


class PluginRequest(BaseModel):
    """
    Written by the core as JSON to the plugin's stdin.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    protocol: Annotated[int, Field(ge=1)]
    action: Literal["collect", "test"]
    config: dict[str, Any]
    """
    Values of the manifest fields, keyed by field key.
    """
    state_dir: str | None = None
    """
    Writable directory private to this integration, kept between runs (e.g. to cache sessions).
    """


class Host(BaseModel):
    """
    An end device observed on the network, with whatever could be learned about it.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    ip: str
    mac: Annotated[str | None, Field(pattern="^[0-9a-f]{2}(:[0-9a-f]{2}){5}$")] = None
    """
    Lowercase, colon separated: aa:bb:cc:dd:ee:ff.
    """
    hostnames: list[str] | None = None
    """
    Names from DNS, mDNS, NetBIOS, DHCP...
    """
    vendor: str | None = None
    """
    Hardware vendor (e.g. from the MAC prefix).
    """
    manufacturer: str | None = None
    """
    Manufacturer reported by the device itself (UPnP).
    """
    model: str | None = None
    os: str | None = None
    open_ports: list[OpenPort] | None = None
    services: list[str] | None = None
    """
    Advertised services, e.g. mDNS types like _airplay._tcp.
    """
    sources: list[str] | None = None
    """
    How the host was found: arp, icmp, tcp, dns, mdns, ssdp, netbios, snmp.
    """
    titles: list[str] | None = None
    """
    Titles of the web interfaces found on the host (e.g. "TrueNAS", "Proxmox Virtual Environment").
    """
    ttl: Annotated[int | None, Field(ge=1, le=255)] = None
    """
    TTL of ICMP replies: hints the OS family (64 Unix-like, 128 Windows, 255 network gear).
    """
    banners: list[str] | None = None
    """
    Service banners, e.g. the SSH version string.
    """
    web: list[WebService] | None = None
    """
    Web interfaces found on the host, one per port.
    """
    dhcp: DhcpFingerprint | None = None


class Device(BaseModel):
    """
    Vendor-neutral snapshot of one network device, as collected by an integration.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    key: str
    """
    Stable unique id of the device within its integration (e.g. base MAC or serial).
    """
    name: str
    host: str | None = None
    """
    Management IP or hostname.
    """
    role: Literal["router", "switch", "ap", "firewall", "server", "unknown"] | None = None
    vendor: str | None = None
    model: str | None = None
    os_version: str | None = None
    serial: str | None = None
    uptime_s: Annotated[int | None, Field(ge=0)] = None
    cpu_pct: Annotated[float | None, Field(ge=0.0, le=100.0)] = None
    mem_pct: Annotated[float | None, Field(ge=0.0, le=100.0)] = None
    cpu_count: Annotated[int | None, Field(ge=1)] = None
    """
    Logical CPUs (cores or threads); for a virtual machine or container, its vCPUs.
    """
    mem_total_bytes: Annotated[int | None, Field(ge=0)] = None
    """
    Memory installed (or given to a virtual machine or container).
    """
    mem_used_bytes: Annotated[int | None, Field(ge=0)] = None
    """
    Memory in use.
    """
    swap_pct: Annotated[float | None, Field(ge=0.0, le=100.0)] = None
    """
    Swap in use.
    """
    load_avg: Annotated[list[float] | None, Field(max_length=3)] = None
    """
    System load averages over 1, 5 and 15 minutes.
    """
    temperatures: list[Temperature] | None = None
    """
    Temperature sensors (CPU cores, disks, board).
    """
    storage: list[Storage] | None = None
    """
    Mounted file systems / volumes.
    """
    firmware: Firmware | None = None
    macs: list[MacAddress] | None = None
    """
    All MAC addresses owned by the device.
    """
    ips: list[str] | None = None
    """
    All IP addresses owned by the device.
    """
    interfaces: list[Interface] | None = None
    neighbors: list[Neighbor] | None = None
    fdb: list[FdbEntry] | None = None
    arp: list[ArpEntry] | None = None
    dhcp_leases: list[DhcpLease] | None = None
    wireless_clients: list[WirelessClient] | None = None
    gateways: list[Gateway] | None = None
    """
    Upstream gateways monitored by a router or firewall.
    """
    hosts: list[Host] | None = None
    """
    End devices observed by this integration with extra details (network scans, controllers).
    """
    vlans: list[Vlan] | None = None
    """
    VLANs defined on the device.
    """
    services: list[Service] | None = None
    """
    Services running (or stopped) on the device.
    """
    vpn_peers: list[VpnPeer] | None = None
    """
    VPN tunnels and peers.
    """
    dhcp_pools: list[DhcpPool] | None = None
    """
    Usage of each DHCP range.
    """
    firewall_states: FirewallStates | None = None


class PluginResponse(BaseModel):
    """
    Written by the plugin as JSON to stdout. Exactly one of devices (collect), message (test) or error is set.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    devices: list[Device] | None = None
    message: str | None = None
    error: str | None = None
